name-template: "moors $RESOLVED_VERSION"
tag-template:  "moors-$RESOLVED_VERSION"
tag-prefix:    "moors-"
filter-by-commitish: true
include-paths:
  - "moors/"

no-changes-template: "* No changes (no merged PRs touching moors/**)"
template: |
  ## Changes
  $CHANGES
