name-template: "moors $RESOLVED_VERSION"
tag-template:  "moors-$RESOLVED_VERSION"
tag-prefix:    "moors-"
filter-by-commitish: true

# cuerpo mínimo y un mensaje claro si no hay cambios
no-changes-template: "* No changes (check filters and tags)"
template: |
  ## Changes
  $CHANGES
