name-template: "pymoors $RESOLVED_VERSION"
tag-template:  "pymoors-$RESOLVED_VERSION"
tag-prefix:    "pymoors-"
filter-by-commitish: true

no-changes-template: "* No changes (check filters and tags)"
template: |
  ## Changes
  $CHANGES
