name-template: "moors $RESOLVED_VERSION"
tag-template: "moors-$RESOLVED_VERSION"
tag-prefix: "moors-"

include-paths:
  - "moors/**"

include-labels:
  - relnotes-feature
  - relnotes-change
  - relnotes-performance
  - relnotes-fix

categories:
  - title: New Features
    labels: [relnotes-feature]
  - title: Changes
    labels: [relnotes-change]
  - title: Performance
    labels: [relnotes-performance]
  - title: Fixes
    labels: [relnotes-fix]

version-resolver:
  major:   { labels: ["major"] }
  minor:   { labels: ["minor"] }
  patch:   { labels: ["patch"] }
  default: patch

template: |
  ## What’s Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
