name-template: "pymoors $RESOLVED_VERSION"
tag-template: "pymoors-$RESOLVED_VERSION"
tag-prefix: "pymoors-"

include-paths:
  - "pymoors/**"

exclude-labels:
  - relnotes-ignore
  - documentation

categories:
  - title: New Features
    labels: [relnotes-feature]
  - title: Changes
    labels: [relnotes-change]
  - title: Performance
    labels: [relnotes-performance]
  - title: Fixes
    labels: [relnotes-fix]

version-resolver:
  major:   { labels: ["major"] }
  minor:   { labels: ["minor"] }
  patch:   { labels: ["patch"] }
  default: patch

template: |
  ## What’s Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
