name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

env:
  DEFAULT_PYTHON: 3.12

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install pymoors
        run: |
          uv sync --group docs
          make build-dev

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
