name: Release Drafter (update drafts)

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize]

concurrency:
  group: release-drafter
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-moors.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-pymoors.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
