name: Publish to crates.io

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: moors

jobs:
  publish:
    name: Publish 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # make sure everything builds in release
          cargo build --release
          cargo publish
