name: Release Drafter

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Update draft (moors)
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-moors.yaml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update draft (pymoors)
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-pymoors.yaml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
