name: Publish crates

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: moors

jobs:
  publish-macros:
    if: startsWith(github.event.release.tag_name, 'moors_macros-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: moors/moors_macros
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build macros crate
        run: cargo build --release
      - name: Publish moors_macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  publish-moors:
    if: startsWith(github.event.release.tag_name, 'moors-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: moors
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build moors crate
        run: cargo build --release
      - name: Publish moors
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
