name: Publish to crates.io

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: moors

jobs:
  publish:
    # only proceed if this is a “moors-…” release
    if: startsWith(github.event.release.tag_name, 'moors-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
